/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_EnergyMetric */

#ifndef _Included_util_EnergyMetric
#define _Included_util_EnergyMetric
#ifdef __cplusplus
extern "C" {
#endif
#undef util_EnergyMetric_MSR_PKG_ENERGY_STATUS
#define util_EnergyMetric_MSR_PKG_ENERGY_STATUS 1553L
/*
 * Class:     util_EnergyMetric
 * Method:    open_msr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_util_EnergyMetric_open_1msr
  (JNIEnv *, jclass, jint);

/*
 * Class:     util_EnergyMetric
 * Method:    read_msr
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_util_EnergyMetric_read_1msr
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     util_EnergyMetric
 * Method:    profileInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_util_EnergyMetric_profileInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
