/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnergyMetric */

#ifndef _Included_EnergyMetric
#define _Included_EnergyMetric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnergyMetric
 * Method:    getCPUEnergy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_EnergyMetric_getCPUEnergy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
